name: The Traveling Programmer

description: My name is Helene. Welcome to my nook in the internet, I 
dont know how you found me, but I'm glad you did. I post about traveling
and programminig and life in general so, stick around for a new 
adventure I plan on taking in my life. You never know what might happen
next.